citation/urls.py
from django.conf.urls import url

from .views import *


app_name = 'citation'
urlpatterns = [
    url(r'^$', CitationList.as_view(), name='list'),
    url(r'^create/?$', CitationCreate.as_view(), name='create'),
    url(r'^(?P<slug>[-\w]+)/update/?$', CitationUpdate.as_view(), name='edit'),
    url(r'^(?P<slug>[-\w]+)/delete/?$', CitationDelete.as_view(), name='delete'),
    url(r'^(?P<slug>[-\w]+)/?$', CitationDetail.as_view(), name='detail'),
]

citation_manager/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('user.urls')),
    url(r'^', include('citation.urls')),
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout_then_login

from .views import *


app_name = 'user'

urlpatterns = [
    url(r'^register/?$', Register.as_view(), name='register'),
    url(r'^login/?$', custom_login, name='login'),
    url(r'^logout/?$', logout_then_login, name='logout'),
]

citation/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User

from _common.models.abstract_models import TimeStampedModel, TextAndPreviewTextModel, SlugModel


class Citation(TimeStampedModel,
               TextAndPreviewTextModel,
               SlugModel):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('citation:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        unique_together = ('user', 'slug')

citation/forms.py
from django import forms

from .models import Citation


class CitationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['content'].widget.attrs = {
            'class': 'materialize-textarea',
        }

    class Meta:
        model = Citation
        fields = ['title', 'content']

citation/views.py
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy

from .forms import CitationForm
from .models import Citation


class CitationList(generic.ListView):
    model = Citation

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Citation.objects.filter(user=self.request.user)


class CitationCreate(generic.CreateView):
    model = Citation
    form_class = CitationForm
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CitationUpdate(generic.UpdateView):
    model = Citation
    form_class = CitationForm
    template_name_suffix = '_update_form'

    def get_queryset(self):
        return Citation.objects.filter(user=self.request.user)

    def form_valid(self, form):
        messages.success(self.request, 'Citation Updated Successfully')
        return super().form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CitationDetail(generic.DetailView):
    model = Citation
    slug_field = 'slug'

    def get_queryset(self):
        return Citation.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CitationDelete(generic.DeleteView):
    model = Citation
    success_url = reverse_lazy('citation:list')

    def get_queryset(self):
        return Citation.objects.filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Citation Deleted')
        return super().delete(request, *args, **kwargs)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

templates/citation/citation_confirm_delete.html
{% extends 'base.html' %}


{% block page %}
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete this citation?</p>
        <button class="waves-effect waves-light btn" type="submit">Yes</button>
        <a href="{% url 'citation:detail' object.slug %}">No</a>
    </form>
{% endblock %}

templates/citation/citation_create_form.html
{% extends 'base.html' %}


{% block page %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
    <button class="waves-effect waves-light btn" type="submit">Add Citation</button>
    <a href="{% url 'citation:list' %}">Cancel</a>
    </form>
{% endblock %}

templates/citation/citation_detail.html
{% extends 'base.html' %}


{% block page %}
    <h1>{{ object.title }}</h1>
    <small>{{ object.created | date }}</small>
    <p>{{ object.content }}</p>
    <a class="waves-effect waves-light btn" href="{% url 'citation:edit' object.slug %}">Edit</a>
    <a class="waves-effect waves-light btn" href="{% url 'citation:delete' object.slug %}">Delete</a>
    <a class="waves-effect waves-light btn" href="{% url 'citation:list' %}">Back</a>
{% endblock %}

templates/citation/citation_list.html
{% extends 'base.html' %}

{% block page %}
    <h1>Citation list</h1>
    <table class="bordered highlight">
        <tbody>

        {% for citation in object_list %}
            <tr>
                <td>
                    <a href="{% url 'citation:detail' citation.slug %}">{{ citation.title }}</a>
                </td>
                <td>
                    <a href="{% url 'citation:edit' citation.slug %}"><i class="material-icons">mode_edit</i></a>
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    <a class="waves-effect waves-light btn" href="{% url 'citation:create' %}"><i class="material-icons left">add</i> Add New</a>
{% endblock %}

templates/citation/citation_update_form.html
{% extends 'base.html' %}


{% block page %}
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="waves-effect waves-light btn" type="submit"><i class="material-icons left">done</i>Save</button>
        <button class="waves-effect waves-light btn" type="reset"><i class="material-icons left">settings_backup_restore</i>Revert Changes</button>
        <a class="waves-effect waves-light btn" href="{% url 'citation:detail' object.slug %}">Cancel</a>
    </form>
{% endblock %}